//
// This file is part of EVEOps.
//
// EVEOps is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3 or later.
//
// Copyright (c) 2026 CitizenCoder
//

import SwiftUI

/// When a card's insight should be (re)generated.
enum AIInsightAutoGenerate {
    /// Generate once, the first time the card appears — further `taskID` changes are ignored
    /// unless the user taps regenerate. Matches how most insight cards behave.
    case once
    /// Regenerate every time `taskID` changes (clearing the previous result first) — for cards
    /// whose subject changes under the user, e.g. browsing between market items.
    case onEveryChange
}

/// Shared "AI Insight" card: header, loading/error states, the generate/regenerate button,
/// and the purple-accented card chrome. Finance/Combat/Industry/Asset/Market/Fitting insight
/// panels each reimplemented this independently before — this is the one copy; domain screens
/// supply only what's specific to them (how to fetch the insight, how to render it).
struct AIInsightCard<Insight, Content: View>: View {
    let loadingMessage: String
    let taskID: AnyHashable
    var autoGenerate: AIInsightAutoGenerate = .once
    /// Gate on whether auto-generation should run for the current `taskID` (e.g. "an item is
    /// actually selected"). The card still renders — this only suppresses the automatic fetch.
    var shouldAutoGenerate: () -> Bool = { true }
    let generate: () async throws -> Insight
    @ViewBuilder let content: (Insight) -> Content

    @State private var insight: Insight?
    @State private var isGenerating = false
    @State private var generationError: String?
    @State private var hasAutoGenerated = false

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            header

            if isGenerating {
                HStack(spacing: 8) {
                    ProgressView()
                        .controlSize(.small)
                    Text(loadingMessage)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            } else if let insight {
                content(insight)
            } else if let generationError {
                Text(generationError)
                    .font(.caption)
                    .foregroundStyle(.red.opacity(0.8))
            } else {
                Button("Generate Insight") {
                    Task { await runGenerate() }
                }
                .buttonStyle(.bordered)
                .controlSize(.small)
            }
        }
        .padding(12)
        .frame(maxWidth: .infinity, alignment: .leading)
        .eveCard()
        .overlay(RoundedRectangle(cornerRadius: EVERadius.xl).strokeBorder(.purple.opacity(0.2)))
        .task(id: taskID) {
            switch autoGenerate {
            case .once:
                guard !hasAutoGenerated, shouldAutoGenerate() else { return }
                hasAutoGenerated = true
                await runGenerate()
            case .onEveryChange:
                guard shouldAutoGenerate() else { return }
                insight = nil
                generationError = nil
                await runGenerate()
            }
        }
    }

    private var header: some View {
        HStack {
            Label("AI Insight", systemImage: "sparkles")
                .font(.subheadline.bold())
                .foregroundStyle(.purple)
            Spacer()
            if insight != nil, !isGenerating {
                Button {
                    Task { await runGenerate() }
                } label: {
                    Image(systemName: "arrow.clockwise")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                .accessibilityLabel("Regenerate insight")
                .buttonStyle(.plain)
                .help("Regenerate insight")
            }
        }
    }

    private func runGenerate() async {
        isGenerating = true
        generationError = nil
        do {
            insight = try await generate()
        } catch is IntelligenceDeclinedError {
            generationError = "Apple Intelligence declined to summarize this data."
        } catch {
            generationError = "Unable to generate insight. Try again later."
        }
        isGenerating = false
    }
}

/// Renderer for the common "summary + lightbulb suggestion" insight shape shared by
/// most `AIInsightCard` users (finance, combat, industry, assets, market, fittings).
struct StandardInsightBody: View {
    let summary: String
    let suggestion: String

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(summary)
                .font(.subheadline)
                .fixedSize(horizontal: false, vertical: true)
            HStack(alignment: .top, spacing: 6) {
                Image(systemName: "lightbulb.fill")
                    .font(.caption)
                    .foregroundStyle(.yellow)
                    .padding(.top, 1)
                Text(suggestion)
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
    }
}
