//
// This file is part of EVEOps.
//
// EVEOps is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3 or later.
//
// Copyright (c) 2026 CitizenCoder
//

import SwiftUI
import Charts
import FoundationModels


// MARK:  Data Models

struct CharacterFinanceData {
    let characterID: Int
    let characterName: String
    let corporationName: String
    let balance: Double
    let journal: [ESIWalletJournalEntry]
    let transactions: [ESIWalletTransaction]
    let marketOrders: [ESIMarketOrder]
    let loyaltyPoints: [ResolvedLoyaltyPoints]
    /// Estimated total asset value using ESI market average prices. Populated after initial load.
    var assetValue: Double = 0
    /// Non-nil when one or more ESI fields failed to fetch; some displayed data may be missing.
    var partialLoadWarning: String? = nil

    var totalEscrow: Double {
        marketOrders.filter { $0.isBuyOrder ?? false }.compactMap(\.escrow).reduce(0, +)
    }

    var totalSellOrderValue: Double {
        marketOrders.filter { !($0.isBuyOrder ?? false) }.reduce(0) { $0 + $1.price * Double($1.volumeRemain) }
    }

    var totalBuyOrderValue: Double {
        marketOrders.filter { $0.isBuyOrder ?? false }.reduce(0) { $0 + $1.price * Double($1.volumeRemain) }
    }
}

struct ResolvedLoyaltyPoints {
    let corporationId: Int
    let corporationName: String
    let loyaltyPoints: Int
}

struct BalancePoint {
    let date: Date
    let balance: Double
}

struct WealthCategory: Identifiable {
    let id = UUID()
    let name: String
    let value: Double
    let color: Color
}

// Mark:  Finance AI Insight Card

@available(macOS 26.0, *)
struct FinanceAIInsightCard: View {
    let finance: CharacterFinanceData
    let netWorth: Double

    @AppStorage("aiInsightsEnabled") private var aiInsightsEnabled = false
    @AppStorage("aiInsightFinances") private var aiInsightFinances = true
    @State private var insight: FinanceInsight?
    @State private var isGenerating = false
    @State private var generationError: String?
    @State private var hasAutoGenerated = false

    private var model: SystemLanguageModel { .default }

    var body: some View {
        if aiInsightsEnabled && aiInsightFinances, case .available = model.availability {
            VStack(alignment: .leading, spacing: 10) {
                HStack {
                    Label("AI Insight", systemImage: "sparkles")
                        .font(.subheadline.bold())
                        .foregroundStyle(.purple)
                    Spacer()
                    if insight != nil, !isGenerating {
                        Button {
                            Task { await generate() }
                        } label: {
                            Image(systemName: "arrow.clockwise")
                                .font(.caption)
                                .foregroundStyle(.secondary)
                        }
                        .buttonStyle(.plain)
                        .help("Regenerate insight")
                    }
                }

                if isGenerating {
                    HStack(spacing: 8) {
                        ProgressView()
                            .controlSize(.small)
                        Text("Analyzing finances\u{2026}")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                } else if let insight {
                    VStack(alignment: .leading, spacing: 8) {
                        Text(insight.summary)
                            .font(.subheadline)
                            .fixedSize(horizontal: false, vertical: true)

                        HStack(alignment: .top, spacing: 6) {
                            Image(systemName: "lightbulb.fill")
                                .font(.caption)
                                .foregroundStyle(.yellow)
                                .padding(.top, 1)
                            Text(insight.suggestion)
                                .font(.caption)
                                .foregroundStyle(.secondary)
                                .fixedSize(horizontal: false, vertical: true)
                        }
                    }
                } else if let error = generationError {
                    Text(error)
                        .font(.caption)
                        .foregroundStyle(.red.opacity(0.8))
                } else {
                    Button("Generate Insight") {
                        Task { await generate() }
                    }
                    .buttonStyle(.bordered)
                    .controlSize(.small)
                }
            }
            .padding(12)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(.regularMaterial, in: RoundedRectangle(cornerRadius: 12))
            .overlay(RoundedRectangle(cornerRadius: 12).strokeBorder(.purple.opacity(0.2)))
            .task(id: finance.characterID) {
                guard !hasAutoGenerated else { return }
                hasAutoGenerated = true
                await generate()
            }
        }
    }

    private func generate() async {
        isGenerating = true
        generationError = nil

        // Sort by raw value on main actor, then format before crossing actor boundary
        let grouped = Dictionary(grouping: finance.journal) { $0.refType }
        let topRefs = grouped.map { refType, entries in
            (name: refType.replacingOccurrences(of: "_", with: " ").capitalized,
             total: entries.compactMap(\.amount).reduce(0, +))
        }
        .sorted { abs($0.total) > abs($1.total) }
        .prefix(5)
        .map { (name: $0.name, totalFormatted: EVEFormatters.formatISKShort($0.total)) }

        do {
            insight = try await IntelligenceService.shared.analyzeFinances(
                characterName: finance.characterName,
                balanceFormatted: EVEFormatters.formatISKShort(finance.balance),
                netWorthFormatted: EVEFormatters.formatISKShort(netWorth),
                sellOrderCount: finance.marketOrders.filter { !($0.isBuyOrder ?? false) }.count,
                buyOrderCount: finance.marketOrders.filter { $0.isBuyOrder ?? false }.count,
                topRefTypes: topRefs
            )
        } catch {
            generationError = "Unable to generate insight. Try again later."
        }
        isGenerating = false
    }
}

// MARK:  Wallet Category Colours

extension WalletCategory {
    var color: Color {
        switch self {
        case .bountiesMissions: return .green
        case .market:           return .blue
        case .industry:         return .orange
        case .contracts:        return .purple
        case .planetary:        return .mint
        case .insurance:        return .teal
        case .corporation:      return .indigo
        case .feesTaxes:        return .red
        case .transfers:        return .cyan
        case .other:            return .gray
        }
    }
}
