//
// This file is part of EVEOps.
//
// EVEOps is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3 or later.
//
// Copyright (c) 2026 CitizenCoder
//

import SwiftUI
import FoundationModels
import OSLog

// MARK:  Browser Mode

enum BrowserMode: String {
    case skills, tree, shipGoal
}

// MARK:  Data Model

struct SkillPlanItem: Identifiable, Codable, Equatable {
    let skillId: Int
    let skillName: String
    let fromLevel: Int
    var targetLevel: Int

    var id: Int { skillId }
}

// Mark:  Skill Plan AI Insight Card

@available(macOS 26.0, *)
struct SkillPlanAIInsightCard: View {
    let characterInfo: CharacterTrainingInfo
    var onAddSkill: ((SkillPlanItem) -> Void)? = nil

    @AppStorage("aiInsightsEnabled") private var aiInsightsEnabled = false
    @AppStorage("aiInsightSkills")   private var aiInsightSkills   = true
    @State private var recommendation: SkillTrainingRecommendation?
    @State private var isGenerating = false
    @State private var generationError: String?
    @State private var hasAutoGenerated = false
    @State private var resolvingIndices: Set<Int> = []
    @State private var addedIndices: Set<Int> = []

    private var model: SystemLanguageModel { .default }

    var body: some View {
        if aiInsightsEnabled && aiInsightSkills, case .available = model.availability {
            VStack(alignment: .leading, spacing: 8) {
                HStack {
                    Label("AI Insight", systemImage: "sparkles")
                        .font(.caption.bold())
                        .foregroundStyle(.purple)
                    Spacer()
                    if recommendation != nil, !isGenerating {
                        Button {
                            Task { await generate() }
                        } label: {
                            Image(systemName: "arrow.clockwise")
                                .font(.system(size: 10))
                                .foregroundStyle(.secondary)
                        }
                        .buttonStyle(.plain)
                        .help("Regenerate insight")
                    }
                }

                if isGenerating {
                    HStack(spacing: 6) {
                        ProgressView()
                            .controlSize(.mini)
                        Text("Analyzing skills\u{2026}")
                            .font(.caption2)
                            .foregroundStyle(.secondary)
                    }
                } else if let rec = recommendation {
                    VStack(alignment: .leading, spacing: 6) {
                        if !rec.playstyleSummary.isEmpty {
                            Text(rec.playstyleSummary)
                                .font(.caption)
                                .fixedSize(horizontal: false, vertical: true)

                            Divider()
                        }

                        ScrollView {
                            VStack(alignment: .leading, spacing: 8) {
                                ForEach(Array(rec.recommendations.enumerated()), id: \.offset) { index, item in
                                    HStack(alignment: .top, spacing: 6) {
                                        Text("\(index + 1)")
                                            .font(.system(size: 9, weight: .bold).monospacedDigit())
                                            .foregroundStyle(.white)
                                            .frame(width: 14, height: 14)
                                            .background(.purple.opacity(0.7), in: Circle())
                                            .padding(.top, 1)
                                        VStack(alignment: .leading, spacing: 2) {
                                            Text("\(cleanedSkillName(item.skillName)) → L\(item.targetLevel)")
                                                .font(.caption.bold())
                                                .fixedSize(horizontal: false, vertical: true)
                                            Text(item.rationale)
                                                .font(.caption2)
                                                .foregroundStyle(.secondary)
                                                .fixedSize(horizontal: false, vertical: true)
                                        }
                                        Spacer(minLength: 4)
                                        skillAddButton(index: index, rec: item)
                                    }
                                }
                            }
                            .padding(.bottom, 2)
                            .padding(.trailing, 12)
                        }
                        .frame(maxHeight: 220)
                    }
                } else if let error = generationError {
                    Text(error)
                        .font(.caption2)
                        .foregroundStyle(.red.opacity(0.8))
                } else {
                    Button("Generate Insight") {
                        Task { await generate() }
                    }
                    .buttonStyle(.bordered)
                    .controlSize(.mini)
                }
            }
            .padding(10)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(.regularMaterial, in: RoundedRectangle(cornerRadius: 10))
            .overlay(RoundedRectangle(cornerRadius: 10).strokeBorder(.purple.opacity(0.2)))
            .task(id: characterInfo.characterID) {
                guard !hasAutoGenerated else { return }
                hasAutoGenerated = true
                await generate()
            }
        }
    }

    private func generate() async {
        isGenerating = true
        generationError = nil
        resolvingIndices = []
        addedIndices = []
        defer { isGenerating = false }
        do {
            let allSkills = characterInfo.skillGroups.flatMap { $0.skills }

            // Full level map for the client-side hard filter — never sent to the AI.
            let currentLevels: [String: Int] = allSkills.reduce(into: [:]) { dict, skill in
                dict[skill.name.lowercased()] = skill.trainedLevel
            }

            let topGroups = characterInfo.skillGroups
                .map { group -> (name: String, sp: Int, skillCount: Int, maxedCount: Int) in
                    let sp = group.skills.reduce(0) { $0 + $1.skillpoints }
                    let maxed = group.skills.filter { $0.trainedLevel == 5 }.count
                    return (name: group.groupName, sp: sp, skillCount: group.skills.count, maxedCount: maxed)
                }
                .sorted { $0.sp > $1.sp }
                .prefix(6)
                .map { (name: $0.name, spFormatted: formatSP($0.sp), skillCount: $0.skillCount, maxedCount: $0.maxedCount) }

            // Partial skills (L1–L4) tell the AI exactly where the character stands so it
            // knows what level to recommend as the target.
            let partialSkills = allSkills
                .filter { $0.trainedLevel >= 1 && $0.trainedLevel <= 4 }
                .sorted { $0.skillpoints > $1.skillpoints }
                .prefix(60)
                .map { (name: $0.name, level: $0.trainedLevel) }

            // Maxed skills (L5) — AI must not recommend any of these.
            let maxedSkills = allSkills
                .filter { $0.trainedLevel == 5 }
                .sorted { $0.skillpoints > $1.skillpoints }
                .prefix(40)
                .map { $0.name }

            var rec = try await IntelligenceService.shared.analyzeTrainedSkills(
                characterName: characterInfo.characterName,
                totalSP: characterInfo.totalSP,
                topGroups: Array(topGroups),
                partialSkills: Array(partialSkills),
                maxedSkills: Array(maxedSkills)
            )

            // Hard client-side filter: keep only recommendations where targetLevel > current level.
            rec.recommendations = Array(
                rec.recommendations.filter { item in
                    let cleaned = cleanedSkillName(item.skillName)
                    let current = currentLevels[cleaned.lowercased()] ?? 0
                    return item.targetLevel > current
                }.prefix(5)
            )
            recommendation = rec
        } catch {
            Logger.intelligence.error("Skill insight generation failed: \(error.localizedDescription)")
            generationError = "Unable to generate insight. Try again later."
        }
    }

    private func formatSP(_ sp: Int) -> String {
        if sp >= 1_000_000 { return String(format: "%.1fM SP", Double(sp) / 1_000_000) }
        if sp >= 1_000 { return String(format: "%.0fK SP", Double(sp) / 1_000) }
        return "\(sp) SP"
    }

    @ViewBuilder
    private func skillAddButton(index: Int, rec: SkillRecommendation) -> some View {
        if onAddSkill != nil {
            if resolvingIndices.contains(index) {
                ProgressView()
                    .controlSize(.mini)
                    .frame(width: 16, height: 16)
                    .padding(.top, 1)
            } else if addedIndices.contains(index) {
                Image(systemName: "checkmark.circle.fill")
                    .font(.system(size: 13))
                    .foregroundStyle(.green)
                    .padding(.top, 1)
            } else {
                Button {
                    Task { await resolveAndAdd(index: index, rec: rec) }
                } label: {
                    Image(systemName: "plus.circle")
                        .font(.system(size: 13))
                        .foregroundStyle(.purple.opacity(0.8))
                }
                .buttonStyle(.plain)
                .padding(.top, 1)
                .help("Add to skill plan")
            }
        }
    }

    // Strips any level suffix the on-device model appends to the skill name field despite
    // instructions, e.g. "Caldari Cruiser to Level V" or "Caldari Cruiser IV" → "Caldari Cruiser".
    private func cleanedSkillName(_ raw: String) -> String {
        var s = raw.trimmingCharacters(in: .whitespaces)
        // Phrase patterns: " to Level V", " - Level 4", " (Level 5)", etc.
        for sep in [" to ", " - ", " (level", " (Level", " level", " Level"] {
            if let range = s.range(of: sep, options: .caseInsensitive) {
                s = String(s[..<range.lowerBound]).trimmingCharacters(in: .whitespaces)
                break
            }
        }
        // Trailing standalone Roman numeral: "Caldari Cruiser IV" → "Caldari Cruiser"
        if let range = s.range(of: #"\s+M{0,4}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$"#,
                               options: .regularExpression) {
            s = String(s[..<range.lowerBound])
        }
        return s
    }

    private func resolveAndAdd(index: Int, rec: SkillRecommendation) async {
        resolvingIndices.insert(index)
        defer { resolvingIndices.remove(index) }

        let skillName = cleanedSkillName(rec.skillName)
        let targetLevel = max(1, min(5, rec.targetLevel))

        // Path 1: character has already trained this skill — use real skillId and fromLevel.
        let allSkills = characterInfo.skillGroups.flatMap { $0.skills }
        if let match = allSkills.first(where: { $0.name.lowercased() == skillName.lowercased() }) {
            let fromLevel = match.trainedLevel
            let effectiveTarget = max(targetLevel, fromLevel + 1)
            guard effectiveTarget <= 5, fromLevel < effectiveTarget else { return }
            onAddSkill?(SkillPlanItem(skillId: match.skillId, skillName: match.name,
                                     fromLevel: fromLevel, targetLevel: effectiveTarget))
            addedIndices.insert(index)
            return
        }

        // Path 2: untrained skill — resolve typeId via ESI then add from L0.
        guard let result: ESIIDsResponse = try? await ESIClient.shared.post("/universe/ids/", body: [skillName]),
              let typeEntry = result.inventoryTypes?.first(where: { $0.name.lowercased() == skillName.lowercased() })
        else { return }
        onAddSkill?(SkillPlanItem(skillId: typeEntry.id, skillName: typeEntry.name,
                                 fromLevel: 0, targetLevel: targetLevel))
        addedIndices.insert(index)
    }
}
